camera1_node:
  ros__parameters:

    frame_rate_ms: 32 # 30 fps
    frame_width_px: 11
    frame_height_px: 9

    webcam_port: 0

    camera_topic_name: "/video/raw_data"
    camera_type: "webcam"   # "webcam" or "video_file_read"
    video_file_read_path: "/home/lior/mnt_surveillance/video_file.bin"

