master_node:
  ros__parameters:

    frame_rate_ms: 32 # 30 fps
    frame_width_px: 100
    frame_height_px: 100

    encoded_video_topic_name: "/video/raw_data"
    decoded_video_topic_name: "/video/decoded_data"
    alarm_service_name: "/mnt_alarm_service"
    analyzer_video_topic_name: "/video/decoded_data"

    alarm_over_saturation_flag: false
    alarm_over_saturation_threshold: 1022
    alarm_over_saturation_ratio_threshold: 0.2 # unsigned 10 bits pixel value

    alarm_under_saturation_flag: false
    alarm_under_saturation_threshold: 100 # ratio of pixels with saturation < threshold
    alarm_under_saturation_ratio_threshold: 0.8 # unsigned 10 bits pixel value