master_node:
  ros__parameters:

    frame_rate_ms: 32 # 30 fps
    frame_width_px: 11
    frame_height_px: 9

    encoded_video_topic_name: "/video/raw_data"
    decoded_video_topic_name: "/video/decoded_data"
    alarm_service_name: "/mnt_alarm_service"
    analyzer_video_topic_name: "/video/decoded_data"

    alarm_over_saturation_flag: true
    alarm_over_saturation_threshold: 50000
    alarm_over_saturation_ratio_threshold: 0.2 # unsigned 10 bits pixel value

    alarm_under_saturation_flag: true
    alarm_under_saturation_threshold: 10000 # ratio of pixels with saturation < threshold
    alarm_under_saturation_ratio_threshold: 0.8 # unsigned 10 bits pixel value

    analyzer_print_results_flag: false  # print results in terminal for testing

    recorder_save_video_flag: false
    recorder_save_video_path: "/home/lior/Desktop/mentee_recordings/testtt.bin"


recorder_node:
  ros__parameters:

    topic_name: "/video/raw_data"
    file_path: "/home/lior/Desktop/mentee_recordings/testtt.bin"